name: RelizcSMPHomePlugin
main: net.itsrelizc.smp.homeplugin.Main
version: 1.0.0
author: Relizc
api-version: 1.20
depend: [RelizcBundlerNewAPI]
permissions:
    main.player:
       description: player
       default: true
    main.admin:
       description: admin
       default: op
      